Repository DavideGalilei/gpytranslate, pull requests merged in 2021-05, with the labels that each got.

#3 [ci] Bump python version to 3.9
  .github/workflows/tests.yml
Labels: enhancement

#4 👀 Merge dev -> master | Major Update 1.0.2
  .github/workflows/tests.yml
  .gitignore
  README.md
  examples/example.py
  examples/https_proxy.py
  examples/socks5_proxy.py
  gpytranslate/gpytranslate.py
  gpytranslate/types/translated_object.py
  setup.py
  tests/test_detect.py
  tests/test_translate.py
Labels: enhancement

#6 ❇️ Fixes #5
  .github/workflows/test-suite.yml
  .github/workflows/tests.yml
  gpytranslate/gpytranslate.py
  setup.py
  tests/test_detect.py
  tests/test_translate.py
Labels: enhancement, fix

#8 🕶 Update 1.2.0 - TTS
  README.md
  examples/async/tts.py
  examples/sync/tts.py
  gpytranslate/__init__.py
  gpytranslate/gpytranslate.py
  gpytranslate/sync/sync_translator.py
  gpytranslate/types/__init__.py
  gpytranslate/types/base_translator.py
  requirements.txt
  setup.py
  tests/async/test_tts.py
  tests/sync/test_sync_tts.py
Labels: documentation, enhancement
